# Generated by Django 4.0.6 on 2022-07-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('capacity', models.PositiveIntegerField(verbose_name='Pojemność')),
                ('projector_availability', models.BooleanField(default=False, verbose_name='Dostępność rzutnika')),
            ],
        ),
    ]
